$(function(){
	// 元素选择器
	// $('p').css("background","black");
	// 类选择器
	// $(".c1").css("background","blue");
	// id选择器
	// $("#p1").css("background","yellow");
	// 层级关系
	// 选择前一个元素
	// $("#p3").prev().css('background',"cyan");
	// 选择后一个元素
	// $("#p3").next().css('background',"cyan");
	// 选择前面所有元素
	// $("#p3").prevAll().css('background',"cyan");
	// 选择后面所有元素
	// $("#p3").nextAll().css('background',"cyan");
	// 选择前面所有元素直到
	// $("#p3").prevUntil("#p1").css('background',"cyan");
	// 选择后面所有元素直到
	// $("#p3").nextUntil("#p5").css('background',"cyan");
	// 选择第一个元素
	// $("p").first().css("background","violet");
	// 选择第二个元素
	// $("p").eq(1).css('background',"cyan");
	// 选择最后一个元素
	// $("p").last().css('background',"cyan");
	// 选择所有的后代
	// $('div').children().css('background',"cyan");
	// 父代选择器
	// $('div').parent().css('background',"cyan");
	// 所有的父代都选中
	// $('div').parents().css('background',"cyan");
});
